Company/config/routes.rb
Company::Application.routes.draw do
  
  resources :teams do 
  	resources :employees, only: [:index]
  end
  resources :employees
  resources :employee_profiles


end

Company/app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  supervisor_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Employee < ActiveRecord::Base
  attr_accessible :name, :supervisor_id, :employee_profile_attributes
  accepts_nested_attributes_for :employee_profile

  belongs_to :supervisor, 
  	class_name: "Employee"
  	inverse_of: :subordinates

  has_many :subordinates, 
  	class_name: "Employee", 
  	foreign_key: "supervisor_id"

  has_many :team_memberships

  has_many :teams, 
  	through: :team_memberships

  has_one :employee_profile, 
  	dependent: :destroy

  accepts_nested_attributes_for :employee_profile

  validates :name, :supervisor, presence: :true
end

Company/app/models/employee_profile.rb
# == Schema Information
#
# Table name: employee_profiles
#
#  id           :integer          not null, primary key
#  employee_id  :integer
#  height       :integer
#  favoritefood :string(255)
#  favoriteday  :string(255)
#  dob          :date
#  salary       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class EmployeeProfile < ActiveRecord::Base
  attr_accessible :dob, :favoriteday, :favoritefood, :height, :salary

  belongs_to :employee,
  	foreign_key: :profile_id
  	inverse_of: :employee_profile

  #validates :dob, :favoriteday, :favoritefood, :height, :salary, presence: :true
end

Company/app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  supervisor_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Team < ActiveRecord::Base
  attr_accessible :name, :supervisor_id, :member_ids

  belongs_to :supervisor, 
  	class_name: "Employee"
  	foreign_key: :supervisor_id
  	inverse_of: :team
  
  has_many :team_memberships

  has_many :members, 
  	through: :team_memberships, 
  	source: :employee
end

Company/app/models/team_membership.rb
# == Schema Information
#
# Table name: team_memberships
#
#  id          :integer          not null, primary key
#  employee_id :integer
#  team_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class TeamMembership < ActiveRecord::Base
  attr_accessible :team_id, :employee_id

  belongs_to :employee
  belongs_to :team
end

Company/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Company/app/controllers/employee_profiles_controller.rb
class EmployeeProfilesController < ApplicationController
 #REV: destroy this one.
end

Company/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
    @profile = EmployeeProfile.find_by_employee_id(params[:id])
  end

  def new
    @employee = Employee.new
    @employees = Employee.all
    @teams = Team.all
    3.times { @employee.build_employee_profile }
  end

  def edit
    @employee = Employee.find(params[:id])
    @employees = Employee.all
    @teams = Team.all
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to employee_path(@employee)
    else
      render :new
    end
  end

  def update
    @employee = Employee.find_by_id(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to user_path(@employee)
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end
end

Company/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
    @employees = Employee.all
  end

  def edit
    @team = Team.find(params[:id])
    @employees = Employee.all
  end

  def create
    #fail
    @team = Team.new(params[:team])
    if @team.save
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  def update
    @team = Team.find_by_id(params[:id])
    if @team.update_attributes(params[:team])
      redirect_to team_path(@team)
    else
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path
  end
end

Company/app/helpers/application_helper.rb
module ApplicationHelper
end

Company/app/helpers/employee_profiles_helper.rb
module EmployeeProfilesHelper
end

Company/app/helpers/employees_helper.rb
module EmployeesHelper
end

Company/app/helpers/teams_helper.rb
module TeamsHelper
end

Company/app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :supervisor %><br>
    <%= f.select :supervisor_id, @employees.map { |employee| [employee.name, employee.id] } %><br>
    <%= f.fields_for :employee_profiles do |epf| %>
      <%= epf.label :height, "Height Inches" %><br>
      <%= epf.number_field :height %><br>
      <%= epf.label :salary %><br>
      <%= epf.number_field :salary %><br>
      <%= epf.label :favoritefood, "Favorite Food" %><br>
      <%= epf.text_field :favoritefood %><br>
      <%= epf.label :favoriteday, "Favorite Day" %><br>
      <%= epf.text_field :favoriteday %><br>
      <%= epf.label :dob, "Date of Birth" %><br>
      <%= epf.date_select :dob %><br>
    <% end %>
    <%= f.label :teams, "Teams" %><br>
    <% @teams.each do |team| %>
      <%= check_box_tag 'employee[team_ids][]', team.id, (checked = @employee.teams.include?(team))%> <%= "  #{team.name}" %><br>
    <% end %>
    <%= hidden_field_tag 'employee[team_ids][]' %>
    Subordinates:<br>
    <% @employees.each do |employee| %>
      <%= check_box_tag 'employee[subordinate_ids][]', employee.id, (checked = @employee.subordinates.include?(employee) %><%= "  #{employee.name}" %><br>
    <% end %>
    <%= hidden_field_tag 'employee[subordinate_ids][]' %>

    <%= f.submit %><br>
<% end %>

Company/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |  
<%= link_to 'Back', employees_path %>

Company/app/views/employees/index.html.erb
<h1>All Employees</h1>

<% @employees.each do |employee| %>
<ul>
  <li><b><%= employee.name %></b></li>
  <li>Supervisor: <%= employee.supervisor.name unless employee.supervisor.nil? %></li>
  <li>Subordinates:  
    <ul>
      <% employee.subordinates.each do |subordinate| %>
        <li><%= subordinate.name %></li>
      <% end %>
    </ul>
  </li>
  <li><%= link_to "Show", employee %> | 
  <%= link_to "Edit", edit_employee_path(employee) %> | 
  <%= link_to "Destroy", employee, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>
<% end %>

<br>

<%= link_to 'New Employee', new_employee_path %>

Company/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

Company/app/views/employees/show.html.erb
<h1>Employee</h1>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Supervisor:</b>
  <%= @employee.supervisor.name unless @employee.supervisor.nil? %>
</p>

<p>
  <b>Subordinates:</b>
  <% @employee.subordinates.each do |subordinate| %>
  	<p><%= link_to subordinate.name, employee_path(subordinate) %></p>
  <% end %>
</p>

<p>
  <b>Teams:</b>
  <% @employee.teams.each do |team| %>
  	<p><%= link_to team.name, team_path(team) %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

Company/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>